### PR TITLE
Add async support with embassy

### PR DESCRIPTION
**Pull request by michaelbeaumont**

### CODE REVIEW

**Comment by TheLostLambda** [comment]
Heya! It looks like it's been ages since this has been worked on, but I'm also looking to use this library with Embassy!

Are you still interested in adding async support to this library? Is that something I could help out with? Thanks for the lovely little library!

**Comment by michaelbeaumont** [comment]
Sure! Go for it. This implementation was way too flaky/unreliable but I didn't spend too much time looking into what was going wrong. Very happy to accept PRs.

**Comment by TheLostLambda** [comment]
Sounds good! I'll give things a go with `embedded-hal-async` (should help avoid any dependency on `embassy` in particular) and let you know how it goes! Looks like it should have everything I need as far as async delays go :)

I'll be able to write and test an Embassy example for my RP2040 (Pi Pico), but I might need your help if you'd like another `stm32l0` example as I don't have that hardware around to test!

**Comment by michaelbeaumont** [comment]
Closing in favor of #18/@TheLostLambda's implementation

**Pull request closed without merging**
