### PR TITLE
An actually sane use of async

### PR DESCRIPTION
**Pull request by TheLostLambda**
This should supersede #14 and #17, and it also reverts part of #16 since I discovered my real problem wasn't a timeout as much as it was not building with `--release`.

This is the one to review and merge!

Keeps changes minimal, lowers the initialization-time for DHT22, and adds async where it matters most and can't mess things up!

### CODE REVIEW

**Comment by TheLostLambda** [comment]
@michaelbeaumont Looks like this will need some changes to the CI to use nightly Rust! Let me know what you think of the code and then we can look into fixing the CI!

**Comment by TheLostLambda** [comment]
I think that's the best I can do for the moment on the CI!

Things work on my (slightly older and pinned) version of nightly on my local machine (nightly-2023-04-02), but nightly being nightly means that sometimes those tests won't always pass!

**Comment by michaelbeaumont** [comment]
@TheLostLambda Thanks for this! Do you reckon you can split this up into multiple PRs? I did the timeout revert in a separate PR already. But maybe CI changes, refactor and then the async features?

**Comment by TheLostLambda** [comment]
> @TheLostLambda Thanks for this! Do you reckon you can split this up into multiple PRs? I did the timeout revert in a separate PR already. But maybe CI changes, refactor and then the async features?

Of course! I'll start on that now and go in that order!

**Comment by TheLostLambda** [comment]
@michaelbeaumont Done! Closing in favor of #20, #21, and #22!

**Pull request closed without merging**
